### ISSUE TITLE
Update screenshots

### ISSUE THREAD

**Issue by JordanL2** [JordanL2/ModularCalculatorInterface#28]

**Comment by JordanL2** [comment]
Merged to 1.4.1.

**Comment by JordanL2** [comment]
> where are those screenshots now?

They're in https://github.com/JordanL2/ModularCalculatorInterface/tree/master/screenshots

They're used for the appdata XML, which is mostly used for the app page in Flathub.

**Comment by Ryder17z** [comment]
I should clarify: why are they missing from readme.md here? It's a bummer since people may ignore the project should they stumble on it here instead of flathub
